version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sema
      POSTGRES_DB: sema

    # volumes:
    #   - /var/lib/postgresql/data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 5

    ports:
      - 5432:5432

    networks:
      - sema-dev-network

  api:
    build:
      context: ./lib/api
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: sema
      POSTGRES_DATABASE: sema

    ports:
      - 3333:3333

    networks:
      - sema-dev-network

    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: ./lib/client
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_URL=http://localhost:3000
        - NEXT_PUBLIC_API_URL=http://localhost:3333
        - SERVER_API_URL=http://api:3333
    restart: always
    ports:
      - 3000:3000

    networks:
      - sema-dev-network

networks:
  sema-dev-network:
    driver: "bridge"
