version: "3.3"
services:
  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    volumes:
      - ~/postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 5

    ports:
      - 5432:5432

    networks:
      - sema-dev-network

  api:
    build:
      context: ./lib/api
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

    ports:
      - 3333:3333

    networks:
      - sema-dev-network

    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: ./lib/client
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_URL=${APP_URL}
        - NEXT_PUBLIC_API_URL=${API_URL}
        - SERVER_API_URL=http://api:3333

    ports:
      - 3000:3000

    networks:
      - sema-dev-network

networks:
  sema-dev-network:
    driver: "bridge"
