replicaCount: 3

image:
  repository: cleiton45/sema
  pullPolicy: IfNotPresent
  tag: "api-d046ca7aaef24f694c9ebc71e183c299dd3c3194-1675268554"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1001
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3333
  name: app-api

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: prod-redirect@kubernetescrd
  hosts:
    - host: api.diarioescolar.net.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.diarioescolar.net.br
      secretName: api.diarioescolar.net.br-tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
