apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ .Values.env.APP_DOMAIN }}-crt
spec:
  secretName:  {{ .Values.env.APP_DOMAIN }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.env.APP_DOMAIN }}
  dnsNames:
  -  {{ .Values.env.APP_DOMAIN }}