FROM node:14-alpine


RUN \
    echo "https://mirror.uepg.br/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/main/" >> /etc/apk/repositories && \
    echo "https://mirror.uepg.br/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/community/" >> /etc/apk/repositories

RUN apk update
RUN apk add --no-cache postgresql-client

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN mkdir app && chown -R appuser:appgroup ./app

USER appuser

WORKDIR /app

ENTRYPOINT ["/bin/ash", "-c"]
CMD ["./init.dev.sh"]

EXPOSE 3333
